return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 20,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 3,
  nextobjectid = 61,
  properties = {},
  tilesets = {
    {
      name = "Props",
      firstgid = 1,
      class = "Saw",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 7,
      tiles = {
        {
          id = 0,
          type = "Tile",
          image = "../../assets/images/test.png",
          width = 32,
          height = 32
        },
        {
          id = 1,
          type = "Placeholder",
          image = "../../assets/images/placeholder.png",
          width = 32,
          height = 32
        },
        {
          id = 3,
          type = "Spike",
          image = "../../assets/images/spike.png",
          width = 32,
          height = 16
        },
        {
          id = 4,
          type = "Goal",
          image = "../../assets/images/goal.png",
          width = 32,
          height = 32
        },
        {
          id = 5,
          type = "Saw",
          image = "../../assets/images/saw.png",
          width = 32,
          height = 32
        },
        {
          id = 6,
          type = "Spring",
          image = "../../assets/images/spring.png",
          width = 32,
          height = 32
        },
        {
          id = 7,
          type = "Booster",
          image = "../../assets/images/booster.png",
          width = 32,
          height = 32
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      id = 1,
      name = "Layout",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {
        ["id"] = "removeTiles",
        ["radius"] = 48
      },
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "Spawnpoint",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "Goal",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 129,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 129,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "Spike",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 32,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "InviSpike",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 96,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          gid = 4,
          visible = true,
          properties = {
            ["radius"] = 48
          }
        },
        {
          id = 16,
          name = "InviSpike",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 96,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          gid = 4,
          visible = true,
          properties = {
            ["radius"] = 48
          }
        },
        {
          id = 17,
          name = "Trigger",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {
            ["id"] = "futureSaw",
            ["radius"] = 48
          }
        },
        {
          id = 18,
          name = "FutureSaw",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {
            ["speed"] = 2500
          }
        },
        {
          id = 19,
          name = "Trigger",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {
            ["id"] = "returnSaw",
            ["radius"] = 48
          }
        },
        {
          id = 20,
          name = "Trigger",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {
            ["id"] = "spawnSaw",
            ["radius"] = 64
          }
        },
        {
          id = 23,
          name = "Booster",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 272,
          width = 32,
          height = 32,
          rotation = 90,
          opacity = 1,
          gid = 8,
          visible = true,
          properties = {
            ["speed"] = 4500
          }
        },
        {
          id = 27,
          name = "MovSaw",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {
            ["speed"] = 400
          }
        },
        {
          id = 28,
          name = "Trigger",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {
            ["id"] = "movSaw",
            ["radius"] = 48
          }
        },
        {
          id = 31,
          name = "Booster",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 608,
          width = 32,
          height = 32,
          rotation = -90,
          opacity = 1,
          gid = 8,
          visible = true,
          properties = {
            ["speed"] = -1000
          }
        },
        {
          id = 33,
          name = "Trigger",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {
            ["id"] = "fakeTiles",
            ["radius"] = 48
          }
        },
        {
          id = 34,
          name = "FakeTile",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "FakeTile",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "Booster",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 480,
          width = 32,
          height = 32,
          rotation = 90,
          opacity = 1,
          gid = 8,
          visible = true,
          properties = {
            ["speed"] = 4000
          }
        }
      }
    }
  }
}
