return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 20,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 3,
  nextobjectid = 74,
  properties = {},
  tilesets = {
    {
      name = "Props",
      firstgid = 1,
      class = "Saw",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 8,
      tiles = {
        {
          id = 0,
          type = "Tile",
          image = "../../assets/images/test.png",
          width = 32,
          height = 32
        },
        {
          id = 1,
          type = "Placeholder",
          image = "../../assets/images/placeholder.png",
          width = 32,
          height = 32
        },
        {
          id = 3,
          type = "Spike",
          image = "../../assets/images/spike.png",
          width = 32,
          height = 16
        },
        {
          id = 4,
          type = "Goal",
          image = "../../assets/images/goal.png",
          width = 32,
          height = 32
        },
        {
          id = 5,
          type = "Saw",
          image = "../../assets/images/saw.png",
          width = 32,
          height = 32
        },
        {
          id = 6,
          type = "Spring",
          image = "../../assets/images/spring.png",
          width = 32,
          height = 32
        },
        {
          id = 7,
          type = "Booster",
          image = "../../assets/images/booster.png",
          width = 32,
          height = 32
        },
        {
          id = 8,
          type = "Laser",
          image = "../../assets/images/laser.png",
          width = 32,
          height = 32
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      id = 1,
      name = "Layout",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 24,
          name = "Spawnpoint",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "Goal",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "SpinningPlat",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 1,
          visible = true,
          properties = {
            ["speed"] = 0.5,
            ["width"] = 40
          }
        },
        {
          id = 42,
          name = "SpinningPlat",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 1,
          visible = true,
          properties = {
            ["height"] = 40,
            ["speed"] = 0.5
          }
        },
        {
          id = 44,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "InviSpike",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 608,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          gid = 4,
          visible = true,
          properties = {
            ["radius"] = 64
          }
        },
        {
          id = 55,
          name = "InviSpike",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 608,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          gid = 4,
          visible = true,
          properties = {
            ["radius"] = 64
          }
        },
        {
          id = 56,
          name = "InviSpike",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 608,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          gid = 4,
          visible = true,
          properties = {
            ["radius"] = 64
          }
        },
        {
          id = 57,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "Trigger",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {
            ["id"] = "spawnSaws",
            ["radius"] = 64
          }
        },
        {
          id = 59,
          name = "FutSaws",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "FutSaws",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "FutSaws",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "FutSaws",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "FutSaws",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "FutSaws",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "Trigger",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {
            ["id"] = "deleteMovs",
            ["radius"] = 64
          }
        },
        {
          id = 72,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
