return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 20,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 4,
  nextobjectid = 73,
  properties = {},
  tilesets = {
    {
      name = "Props",
      firstgid = 1,
      class = "Saw",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 5,
      tiles = {
        {
          id = 0,
          type = "Tile",
          image = "../assets/images/test.png",
          width = 32,
          height = 32
        },
        {
          id = 1,
          type = "Placeholder",
          image = "../assets/images/placeholder.png",
          width = 32,
          height = 32
        },
        {
          id = 3,
          type = "Spike",
          image = "../assets/images/spike.png",
          width = 32,
          height = 16
        },
        {
          id = 4,
          type = "Goal",
          image = "../assets/images/goal.png",
          width = 32,
          height = 32
        },
        {
          id = 5,
          type = "Saw",
          image = "../assets/images/saw.png",
          width = 32,
          height = 32
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      id = 1,
      name = "Layout",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "Spawnpoint",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "FakeGoal",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 5,
          visible = true,
          properties = {
            ["newX"] = 800,
            ["newY"] = 576,
            ["radius"] = 64
          }
        },
        {
          id = 44,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "FakeSaw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {
            ["pair"] = 1
          }
        },
        {
          id = 54,
          name = "FakePortal",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "Portal",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {
            ["pair"] = 1
          }
        },
        {
          id = 56,
          name = "FakeSpike",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 96,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "FakeSpike",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 96,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "DeslocSaw",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "DeslocSaw",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "DeslocSaw",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "Trigger",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {
            ["radius"] = 80
          }
        },
        {
          id = 65,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "Saw",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "FakeTile",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "FakeTile",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
